version: "3.8"
services:
  mysql:
    platform: linux/x86_64
    image: library/mysql:8.0.33
    container_name: calcuate-admin-mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: calculate-admin
      MYSQL_USER: soko
      MYSQL_PASSWORD: password
      TZ: Asia/Seoul
    command: ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_general_ci"]

#  redis:
#    platform: linux/x86_64
#    image: library/redis:7.2.1
#    container_name: calculate-admin-redis
#    restart: always
#    ports:
#      - 6379:6379