spring:
  datasource:
    url: jdbc:mysql://localhost:3306/calculate-admin?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: soko
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
